spring:
 datasource:
   driver-class-name: org.postgresql.Driver
   url: jdbc:postgresql://34.64.205.117:5432/postgres
   username: postgres
   password: kwak1234
 thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
    cache: false
    check-template-location: false
 mvc:
    hiddenmethod:
      filter:
        enabled: true
server:
 port: 8090
 servlet:
    encoding:
      force: true
